# Setup
title: Kamil Lee의 개발 일기
description: 일본 장기 AI와 개발 관련 이야기를 중심으로 정리하고 있습니다.
url: https://kamillee0918.github.io
avatar: /avatar.png
paginate: 10
permalink: pretty
cover_image: /bg.png

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-last-modified-at

# Minifier settings
minifier:
  css: true
  html: true
  js: true
  remove_comments: true
  remove_whitespace: true
  remove_newlines: true
  remove_emptyattributes: true
  remove_quotes: true
  remove_script_attributes: true
  remove_style_attributes: true
  remove_link_attributes: true
  remove_form_attributes: true
  remove_input_attributes: true
  remove_javascript_protocol: true
  remove_http_protocol: false
  remove_https_protocol: false
  remove_http_www_protocol: false
  remove_https_www_protocol: false
  uglifier:
    harmony: true
    compress:
      harmony: true
      ecma: 6

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
logo: logo.png
social:
  name: kamillee0918
  links:
    - https://github.com/kamillee0918
# google_site_verification: google04d96c1389a00d91.html  # HTML 파일 방식 사용 시 주석 처리
lang: ko

sass:
  sass_dir: _sass
  style: compressed

# Options

# Google Analytics tracking
google_analytics: G-QMW2B664KQ

# Specify the author for blog posts
author:
  name: kamillee0918
  url: https://github.com/kamillee0918/
  email: parousia0918@gmail.com
